/* TUG-Conference-2018 */

SELECT 
        LOCATION.LOC_NAME                               AS LOC_NAME, 
        DSCP_INCIDENT.DSCP_INCIDENT_REF_PER_ID          AS TEACHER,
        PERSON.PER_LAST_NAME                            AS PER_LAST_NAME, 
        PERSON.PER_FIRST_NAME                           AS PER_FIRST_NAME,
        DSCP_OFFENDER.RFD_DSCP_OFFENSE_NM               AS OFFENSE, 
        DSCP_INCIDENT.DSCP_INCIDENT_FID 											AS INCIDENT_ID,
        
        DSCP_OFFENDER.PER_ID,
        DSCP_OFFENDER.DSCP_OFFENDER_CMNT
    FROM DSCP_INCIDENT
    LEFT JOIN DSCP_OFFENDER
      ON  DSCP_OFFENDER.DSCP_INCIDENT_FID = DSCP_INCIDENT.DSCP_INCIDENT_FID
      AND DSCP_OFFENDER.DSCP_INCIDENT_FISCAL_YR = DSCP_INCIDENT.DSCP_INCIDENT_FISCAL_YR
    LEFT JOIN PERSON
      ON  DSCP_INCIDENT.DSCP_INCIDENT_REF_PER_ID = PERSON.PER_ID
    LEFT JOIN LOCATION
      ON  LOCATION.LOC_ID = DSCP_INCIDENT.DSCP_INCIDENT_INIT_CAMPUS_ID
    WHERE DSCP_INCIDENT.DSCP_INCIDENT_FISCAL_YR = $P{FiscalYear}
      AND DSCP_INCIDENT.DSCP_INCIDENT_INIT_CAMPUS_ID = $P{Campus}
      AND DSCP_INCIDENT.DSCP_INCIDENT_FID IN (
       SELECT 
            DSCP_OFFENDER.DSCP_INCIDENT_FID 
       FROM DSCP_OFFENDER 
       WHERE DSCP_OFFENDER.DSCP_INCIDENT_FISCAL_YR = $P{FiscalYear}
      )
    ORDER BY
            TEACHER,
            OFFENSE,
            INCIDENT_ID
